[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_SPIRAM_BOOT_INIT
    -DLV_CONF_SKIP=1
    -DLV_COLOR_DEPTH=16
    -DLV_COLOR_16_SWAP=0
    -DLV_MEM_SIZE="(64*1024)"
    -DLV_TICK_CUSTOM=1
    -DLV_TICK_CUSTOM_INCLUDE=\"Arduino.h\"
    -DLV_TICK_CUSTOM_SYS_TIME_EXPR="millis()"
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_USE_BTN=1
    -DLV_USE_LABEL=1

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    lvgl/lvgl @ ^8.3.0
    esphome/ESP32-audioI2S @ ^2.0.7

   